import './globals.css'
import { Inter } from 'next/font/google'


export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}


export default function RootLayout(props) {
  const { children } = props;
  return (
    <html lang="en" data-theme="dark" >
      <body className="h-screen	w-screen">{children}</body>
    </html>
  )
}

